name: David Rodriguez
first_name: David
last_name: Rodriguez
theme: jekyll-theme-slate
title: >
  David Rodriguez Portfolio
description: >
  My name is David Rodriguez, I am an aspiring Data Analyst and am currently a student at Brooklyn College.
author:
  name: David Rodriguez

lang: en
