#Name stuff
name: David Rodriguez
first_name: David
last_name: Rodriguez

#theme
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
header:
  background-image: assets\images\sidebar-bg.jpg

#title and description
title: >
  David Rodriguez Portfolio
description: >
  My name is David Rodriguez, I am an aspiring Data Analyst and am currently a student at Brooklyn College.

#menu
menu:
  - title:             Home
    url:               index.md
  - title:             Projects
    url:               page1.md
  - title:             Resume
    url:               page2.md

pages:
  - title: Home
    filename: index.md
  - title: Projects
    filename: page1.md
  - title: Resume
    filename: page2.md

#social
socials:
  - name: 'LinkedIn'
    url: https://www.linkedin.com/in/david-rodriguez-486b95208/
  - name: 'Github'
    url: https://github.com/drod75
  - name: 'Kaggle'
    url: https://www.kaggle.com/drod75
  - name: 'Huggingface'
    url: https://huggingface.co/drod75
  - name: 'Email'
    url: mailto:dr507498@gmail.com

#misc.
url: "https://drod75.github.io/"
show_downloads: False
author:
  name: David Rodriguez
lang: en
