name: My Site
first_name: David
last_name: Rodriguez
theme: jekyll-theme-minimal
email: dr507498@gmail.com
description: >
  A simple site for those who wish to contact to research David Rodriguez, all allowed contact methods are listed.
lang: en