name: My Site
first_name: David
last_name: Rodriguez
theme: jekyll-theme-minimal
description: >
  A simple site for those who wish to contact and research me, all allowed contact methods are listed below.
lang: en