name: David Rodriguez
first_name: David
last_name: Rodriguez
theme: jekyll-theme-slate
title: >
  david-rodriguez-nyc
description: >
  My name is David Rodriguez, I am an aspiring Data Analyst and am currently a student at Brooklyn College.
lang: en
