name: David Rodriguez
first_name: David
last_name: Rodriguez
theme: jekyll-theme-slate
description: >
  A simple site for those who wish to contact and research me, all allowed contact methods are listed below.
lang: en
