#Name stuff
name: David Rodriguez
first_name: David
last_name: Rodriguez

#theme
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
header:
  background-image: assets\images\sidebar-bg.jpg

#title and description
title: >
  David Rodriguez Portfolio

#menu
menu:
  - title:             Home
    url:               index.md

pages:
  - title: Home
    filename: index.md
    
#misc.
url: "https://drod75.github.io/"
show_downloads: False
author:
  name: David Rodriguez
lang: en
